# Generated by Django 4.2.25 on 2026-02-04 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_user_birth_date_user_first_name_user_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretestquestion',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('multiple_choice_image', 'Multiple Choice (Images)'), ('true_false', 'True/False'), ('short_answer', 'Short Answer / Essay'), ('scale', 'Scale (1-6)')], max_length=30),
        ),
    ]
