# Generated by Django 4.2.25 on 2026-02-08 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pretestquestion_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilingArchetype',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Example: PAR, PAI, TAR, etc.', max_length=3, unique=True)),
                ('archetype_name', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
        ),
    ]
