# Generated by Django 4.2.25 on 2026-02-12 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_pretestquestion_weight_abstraction_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_type', models.CharField(choices=[('INTSE', 'INTSE'), ('INTSS', 'INTSS'), ('INTST', 'INTST'), ('SE', 'SE'), ('SS', 'SS'), ('ST', 'ST')], max_length=10)),
                ('class_number', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Student Class',
                'verbose_name_plural': 'Student Classes',
                'ordering': ['class_type', 'class_number'],
                'unique_together': {('class_type', 'class_number')},
            },
        ),
    ]
