# Generated by Django 4.2.25 on 2026-02-19 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_user_cog_ga_value_user_cog_ir_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pretestresponse',
            name='response_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
