# Generated by Django 4.2.25 on 2026-02-20 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_quizquestion_category_quizquestion_correctans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='core.course'),
            preserve_default=False,
        ),
    ]
