# Generated by Django 4.2.25 on 2026-02-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_delete_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilingarchetype',
            name='cognitive_description',
            field=models.TextField(blank=True, help_text='Long description for Cognitive Description section', null=True),
        ),
        migrations.AddField(
            model_name='profilingarchetype',
            name='strengths',
            field=models.JSONField(blank=True, default=list, help_text='List of strength strings'),
        ),
        migrations.AddField(
            model_name='profilingarchetype',
            name='tactics',
            field=models.JSONField(blank=True, default=list, help_text="List of tactic names, e.g. ['Step-by-Step', 'Planner']"),
        ),
        migrations.AddField(
            model_name='profilingarchetype',
            name='tactics_description',
            field=models.TextField(blank=True, help_text='Short description for the Tactics panel', null=True),
        ),
        migrations.AddField(
            model_name='profilingarchetype',
            name='weaknesses',
            field=models.JSONField(blank=True, default=list, help_text='List of weakness strings'),
        ),
    ]
