# Generated by Django 4.2.25 on 2026-02-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_profilingarchetype_cognitive_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilingarchetype',
            name='tactics_image',
            field=models.CharField(blank=True, help_text='Public path to tactics image, e.g. /images/traits/PAR 2.png', max_length=255, null=True),
        ),
    ]
