# Generated by Django 4.2.7 on 2026-02-25 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_quizquestion_admin_feedback_quizquestion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.material'),
        ),
    ]
