# Generated by Django 4.2.25 on 2026-03-04 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_move_week_from_material_to_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='material',
        ),
    ]
