# Generated by Django 4.2.25 on 2026-02-02 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_otp_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretestquestion',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General Pretest'), ('PROFILING_PEDAGOGY', 'Profiling: Pedagogy'), ('PROFILING_COGNITIVE_TP', 'Profiling: Cognitive TP'), ('PROFILING_COGNITIVE_GA', 'Profiling: Cognitive GA'), ('PROFILING_COGNITIVE_IR', 'Profiling: Cognitive IR')], default='GENERAL', max_length=30),
        ),
        migrations.AddField(
            model_name='pretestquestion',
            name='level',
            field=models.IntegerField(default=1, help_text='Level 1-6 for Pedagogy'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_profiled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pretestquestion',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('true_false', 'True/False'), ('short_answer', 'Short Answer'), ('scale', 'Scale 1-6')], max_length=20),
        ),
    ]
