# Generated by Django 4.2.25 on 2026-02-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_pretestquestion_category_pretestquestion_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretestquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
    ]
