# Generated by Django 4.2.25 on 2026-02-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_seed_archetypes'),
    ]

    operations = [
        migrations.CreateModel(
            name='PedagogyLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
    ]
