# Generated by Django 4.2.25 on 2026-02-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_seed_pedagogy_levels'),
    ]

    operations = [
        migrations.AddField(
            model_name='pretestquestion',
            name='weight_abstraction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pretestquestion',
            name='weight_algorithm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pretestquestion',
            name='weight_decomposition',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pretestquestion',
            name='weight_pattern',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='ct_abstraction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='ct_algorithm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='ct_decomposition',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='user',
            name='ct_pattern',
            field=models.FloatField(default=0.0),
        ),
    ]
