# Generated by Django 4.2.25 on 2026-02-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_studentclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cog_ga_value',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='user',
            name='cog_ir_value',
            field=models.FloatField(default=50.0),
        ),
        migrations.AddField(
            model_name='user',
            name='cog_tp_value',
            field=models.FloatField(default=50.0),
        ),
    ]
