# Generated by Django 4.2.25 on 2026-02-19 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_seed_student_classes'),
        ('core', '0017_alter_pretestresponse_response_value'),
    ]

    operations = [
    ]
