# Generated by Django 4.2.25 on 2026-02-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='category',
            field=models.CharField(choices=[('GENERAL', 'General Quiz'), ('PROFILING_PEDAGOGY', 'Profiling: Pedagogy'), ('PROFILING_COGNITIVE_TP', 'Profiling: Cognitive TP'), ('PROFILING_COGNITIVE_GA', 'Profiling: Cognitive GA'), ('PROFILING_COGNITIVE_IR', 'Profiling: Cognitive IR')], default='GENERAL', max_length=30),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correctAns',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='questions/'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='level',
            field=models.IntegerField(default=1, help_text='Level 1-6 for Pedagogy'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='result',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='score',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='type',
            field=models.CharField(choices=[('multiple_choice', 'Multiple Choice'), ('multiple_choice_image', 'Multiple Choice (Images)'), ('multi_select', 'Multi Select (Checkboxes)'), ('multi_select_image', 'Multi Select (Images)'), ('true_false', 'True/False'), ('short_answer', 'Short Answer / Essay')], default='multiple_choice', max_length=30),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='weight_abstraction',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='weight_algorithm',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='weight_decomposition',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='weight_pattern',
            field=models.FloatField(default=0.0),
        ),
    ]
