# Generated by Django 4.2.25 on 2026-02-20 17:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_quizresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['week', 'order']},
        ),
        migrations.AddField(
            model_name='course',
            name='thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrolled_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='quiz_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='material',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('ppt', 'PowerPoint'), ('other', 'Other')], default='pdf', max_length=10),
        ),
        migrations.AddField(
            model_name='material',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quizresponse',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
