# Generated by Django 4.2.7 on 2026-02-21 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_material_options_course_thumbnail_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Module',
        ),
    ]
