# Generated by Django 4.2.25 on 2026-03-04 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_course_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['week', 'id']},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['order']},
        ),
        migrations.RemoveField(
            model_name='material',
            name='week',
        ),
        migrations.AddField(
            model_name='course',
            name='week',
            field=models.IntegerField(default=1, help_text='Minggu ke berapa course ini dijalankan'),
        ),
    ]
