# Generated by Django 4.2.25 on 2026-03-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_exercisequestion_exercisesession_exerciseresponse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='deadline',
            field=models.DateTimeField(blank=True, help_text='Batas waktu pengerjaan quiz', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.IntegerField(default=1800, help_text='Batas waktu dalam detik (default 30 menit)'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='points',
            field=models.FloatField(default=0.0, help_text='Skor gamifikasi (untuk leaderboard)'),
        ),
        migrations.AddField(
            model_name='quizresult',
            name='time_taken',
            field=models.IntegerField(default=0, help_text='Waktu pengerjaan dalam detik'),
        ),
    ]
