# Generated by Django 4.2.25 on 2026-03-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_quiz_deadline_quiz_time_limit_quizresult_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresponse',
            name='time_taken',
            field=models.IntegerField(default=0, help_text='Waktu pengerjaan soal dalam detik'),
        ),
    ]
