# Generated by Django 4.2.25 on 2026-03-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_material_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='cognitive_style',
            field=models.CharField(blank=True, help_text='Cognitive style for adaptive questions', max_length=10, null=True),
        ),
    ]
