# Generated by Django 4.2.25 on 2026-04-03 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_quizquestion_cognitive_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.studentclass'),
        ),
    ]
