# Generated by Django 4.2.25 on 2026-04-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_quizquestion_cognitive_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Jika False, quiz tidak bisa diakses student'),
        ),
    ]
