# Generated by Django 4.2.25 on 2026-04-03 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_user_student_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='student_class',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
