# Generated by Django 4.2.25 on 2026-04-10 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_quizattempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilingAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField(default=0)),
                ('cognitive_answers', models.JSONField(blank=True, default=dict)),
                ('pedagogic_answers', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('questions', models.ManyToManyField(related_name='profiling_attempts', to='core.pretestquestion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profiling_attempt', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
