# Generated by Django 4.2.25 on 2026-04-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_profilingattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilingattempt',
            name='form_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
