# Generated by Django 4.2.25 on 2026-04-10 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_profilingattempt_form_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilingarchetype',
            name='cognitive_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilingarchetype',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilingarchetype',
            name='strengths_en',
            field=models.JSONField(blank=True, default=list, help_text='List of strength strings in English'),
        ),
        migrations.AddField(
            model_name='profilingarchetype',
            name='tactics_description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profilingarchetype',
            name='weaknesses_en',
            field=models.JSONField(blank=True, default=list, help_text='List of weakness strings in English'),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(choices=[('id', 'Indonesian'), ('en', 'English')], default='id', max_length=5),
        ),
    ]
