# Generated by Django 4.2.25 on 2026-04-10 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_profilingarchetype_cognitive_description_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilingarchetype',
            name='cognitive_description_en',
        ),
        migrations.RemoveField(
            model_name='profilingarchetype',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='profilingarchetype',
            name='strengths_en',
        ),
        migrations.RemoveField(
            model_name='profilingarchetype',
            name='tactics_description_en',
        ),
        migrations.RemoveField(
            model_name='profilingarchetype',
            name='weaknesses_en',
        ),
        migrations.RemoveField(
            model_name='user',
            name='preferred_language',
        ),
    ]
