# Generated by Django 4.2.25 on 2026-04-14 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_remove_profilingarchetype_cognitive_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Kapan quiz mulai bisa diakses', null=True),
        ),
    ]
