# Generated by Django 4.2.25 on 2026-04-14 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_quiz_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='allow_late_submission',
            field=models.BooleanField(default=False, help_text='Jika True, student masih bisa mengerjakan setelah deadline'),
        ),
    ]
